source XML
sampleUsersXML
	^
		'<users>
			<user>
				<Username>jsmith</Username>
				<RealName>John Smith</RealName>
			</user>
			<User>
				<username>msmith</username>
				<realName>Michael Smith</realName>
			</User>
			<user>
				<Username>jsmith2</Username>
				<real-name>James Smith</real-name>
			</user>
			<User>
				<username>rsmith</username>
				<real_name>Robert Smith</real_name>
			</User>
		</users>'.