Class {
	#name : #FmxNGStInvocation,
	#superclass : #FmxNGStAssociation,
	#traits : 'FmxNGTInvocation + FmxNGTWithSignature',
	#classTraits : 'FmxNGTInvocation classTrait + FmxNGTWithSignature classTrait',
	#category : #'FmxNGPharoSmalltalk-Entities-Entities'
}

{ #category : #meta }
FmxNGStInvocation class >> annotation [

	<generated>
	<MSEClass: #Invocation super: #FmxNGStAssociation>
	<package: #'FmxNGPharoSmalltalk-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGStInvocation class >> generatedSlotNames [
	<generated>
	'FmxNGStInvocation class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGStInvocation class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTInvocation FmxNGTWithSignature)
]

{ #category : #meta }
FmxNGStInvocation class >> requirements [

	<generated>
	^ {  }
]
