Class {
	#name : #FmxNGStUnknownVariable,
	#superclass : #FmxNGStStructuralEntity,
	#category : #'FmxNGPharoSmalltalk-Entities-Entities'
}

{ #category : #meta }
FmxNGStUnknownVariable class >> annotation [

	<generated>
	<MSEClass: #UnknownVariable super: #FmxNGStStructuralEntity>
	<package: #'FmxNGPharoSmalltalk-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGStUnknownVariable class >> generatedSlotNames [
	<generated>
	'FmxNGStUnknownVariable class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGStUnknownVariable class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGStUnknownVariable class >> requirements [

	<generated>
	^ {  }
]
