Class {
	#name : #FmxNGStSourceLanguage,
	#superclass : #FmxNGStEntity,
	#traits : 'FmxNGTSourceLanguage',
	#classTraits : 'FmxNGTSourceLanguage classTrait',
	#category : #'FmxNGPharoSmalltalk-Entities-Entities'
}

{ #category : #meta }
FmxNGStSourceLanguage class >> annotation [

	<generated>
	<MSEClass: #SourceLanguage super: #FmxNGStEntity>
	<package: #'FmxNGPharoSmalltalk-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGStSourceLanguage class >> generatedSlotNames [
	<generated>
	'FmxNGStSourceLanguage class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGStSourceLanguage class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTSourceLanguage)
]

{ #category : #meta }
FmxNGStSourceLanguage class >> requirements [

	<generated>
	^ {  }
]

{ #category : #testing }
FmxNGStSourceLanguage >> isSmalltalk [
	^ false
]
