Class {
	#name : #FmxNGStLocalVariable,
	#superclass : #FmxNGStStructuralEntity,
	#traits : 'FmxNGTLocalVariable',
	#classTraits : 'FmxNGTLocalVariable classTrait',
	#category : #'FmxNGPharoSmalltalk-Entities-Entities'
}

{ #category : #meta }
FmxNGStLocalVariable class >> annotation [

	<generated>
	<MSEClass: #LocalVariable super: #FmxNGStStructuralEntity>
	<package: #'FmxNGPharoSmalltalk-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGStLocalVariable class >> generatedSlotNames [
	<generated>
	'FmxNGStLocalVariable class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGStLocalVariable class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTLocalVariable)
]

{ #category : #meta }
FmxNGStLocalVariable class >> requirements [

	<generated>
	^ {  }
]
