Class {
	#name : #FmxNGStPackage,
	#superclass : #FmxNGStScopingEntity,
	#traits : 'FmxNGTPackage',
	#classTraits : 'FmxNGTPackage classTrait',
	#category : #'FmxNGPharoSmalltalk-Entities-Entities'
}

{ #category : #meta }
FmxNGStPackage class >> annotation [

	<generated>
	<MSEClass: #Package super: #FmxNGStScopingEntity>
	<package: #'FmxNGPharoSmalltalk-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGStPackage class >> generatedSlotNames [
	<generated>
	'FmxNGStPackage class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGStPackage class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTPackage)
]

{ #category : #meta }
FmxNGStPackage class >> requirements [

	<generated>
	^ {  }
]
