Class {
	#name : #FmxNGStUnknownSourceLanguage,
	#superclass : #FmxNGStSourceLanguage,
	#category : #'FmxNGPharoSmalltalk-Entities-Entities'
}

{ #category : #meta }
FmxNGStUnknownSourceLanguage class >> annotation [

	<generated>
	<MSEClass: #UnknownSourceLanguage super: #FmxNGStSourceLanguage>
	<package: #'FmxNGPharoSmalltalk-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGStUnknownSourceLanguage class >> generatedSlotNames [
	<generated>
	'FmxNGStUnknownSourceLanguage class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGStUnknownSourceLanguage class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGStUnknownSourceLanguage class >> requirements [

	<generated>
	^ {  }
]
