Class {
	#name : #FmxNGTest2ImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'FmxNGTest2-Entities'
}

{ #category : #generator }
FmxNGTest2ImportingContext class >> generatedSlotNames [
	<generated>
	'FmxNGTest2ImportingContext class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGTest2ImportingContext class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #testing }
FmxNGTest2ImportingContext >> importAssociation [

	<generated>
	^ self import: FmxNGTest2Association
]

{ #category : #testing }
FmxNGTest2ImportingContext >> importClass [

	<generated>
	^ self import: FmxNGTest2Class
]

{ #category : #testing }
FmxNGTest2ImportingContext >> importComment [

	<generated>
	^ self import: FmxNGTest2Comment
]

{ #category : #testing }
FmxNGTest2ImportingContext >> importEntity [

	<generated>
	^ self import: FmxNGTest2Entity
]

{ #category : #testing }
FmxNGTest2ImportingContext >> importInheritance [

	<generated>
	^ self import: FmxNGTest2Inheritance
]

{ #category : #testing }
FmxNGTest2ImportingContext >> importNamedEntity [

	<generated>
	^ self import: FmxNGTest2NamedEntity
]

{ #category : #testing }
FmxNGTest2ImportingContext >> importSourceAnchor [

	<generated>
	^ self import: FmxNGTest2SourceAnchor
]

{ #category : #testing }
FmxNGTest2ImportingContext >> importSourceLanguage [

	<generated>
	^ self import: FmxNGTest2SourceLanguage
]

{ #category : #testing }
FmxNGTest2ImportingContext >> importSourcedEntity [

	<generated>
	^ self import: FmxNGTest2SourcedEntity
]

{ #category : #testing }
FmxNGTest2ImportingContext >> shouldImportAssociation [

	<generated>
	^ self shouldImport: FmxNGTest2Association
]

{ #category : #testing }
FmxNGTest2ImportingContext >> shouldImportClass [

	<generated>
	^ self shouldImport: FmxNGTest2Class
]

{ #category : #testing }
FmxNGTest2ImportingContext >> shouldImportComment [

	<generated>
	^ self shouldImport: FmxNGTest2Comment
]

{ #category : #testing }
FmxNGTest2ImportingContext >> shouldImportEntity [

	<generated>
	^ self shouldImport: FmxNGTest2Entity
]

{ #category : #testing }
FmxNGTest2ImportingContext >> shouldImportInheritance [

	<generated>
	^ self shouldImport: FmxNGTest2Inheritance
]

{ #category : #testing }
FmxNGTest2ImportingContext >> shouldImportNamedEntity [

	<generated>
	^ self shouldImport: FmxNGTest2NamedEntity
]

{ #category : #testing }
FmxNGTest2ImportingContext >> shouldImportSourceAnchor [

	<generated>
	^ self shouldImport: FmxNGTest2SourceAnchor
]

{ #category : #testing }
FmxNGTest2ImportingContext >> shouldImportSourceLanguage [

	<generated>
	^ self shouldImport: FmxNGTest2SourceLanguage
]

{ #category : #testing }
FmxNGTest2ImportingContext >> shouldImportSourcedEntity [

	<generated>
	^ self shouldImport: FmxNGTest2SourcedEntity
]
