Class {
	#name : #FAMIXPrimitiveType,
	#superclass : #FAMIXType,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FAMIXPrimitiveType class >> annotation [

	<generated>
	<MSEClass: #PrimitiveType super: #FAMIXType>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FAMIXPrimitiveType class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FAMIXPrimitiveType class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FAMIXPrimitiveType class >> requirements [

	<generated>
	^ {  }
]

{ #category : #testing }
FAMIXPrimitiveType >> isPrimitiveType [
	^true
]
