Class {
	#name : #FAMIXCaughtException,
	#superclass : #FAMIXException,
	#traits : 'FmxNGTCaughtException',
	#classTraits : 'FmxNGTCaughtException classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FAMIXCaughtException class >> annotation [

	<generated>
	<MSEClass: #CaughtException super: #FAMIXException>
	<package: #FAMIX>
	<generated>
	^self
]

{ #category : #generator }
FAMIXCaughtException class >> generatedSlotNames [
	<generated>
	'FAMIXCaughtException class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FAMIXCaughtException class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTCaughtException)
]

{ #category : #meta }
FAMIXCaughtException class >> requirements [

	<generated>
	^ {  }
]
