Class {
	#name : #FAMIXTraitUsage,
	#superclass : #FAMIXAssociation,
	#traits : 'FmxNGTTraitUsage',
	#classTraits : 'FmxNGTTraitUsage classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FAMIXTraitUsage class >> annotation [

	<generated>
	<MSEClass: #TraitUsage super: #FAMIXAssociation>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FAMIXTraitUsage class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FAMIXTraitUsage class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTTraitUsage)
]

{ #category : #meta }
FAMIXTraitUsage class >> requirements [

	<generated>
	^ {  }
]
