Class {
	#name : #FAMIXCppSourceLanguage,
	#superclass : #FAMIXCSourceLanguage,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FAMIXCppSourceLanguage class >> annotation [

	<generated>
	<MSEClass: #CppSourceLanguage super: #FAMIXCSourceLanguage>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FAMIXCppSourceLanguage class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FAMIXCppSourceLanguage class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FAMIXCppSourceLanguage class >> requirements [

	<generated>
	^ {  }
]
