Class {
	#name : #FAMIXCustomSourceLanguage,
	#superclass : #FAMIXSourceLanguage,
	#traits : 'FmxNGTNamed',
	#classTraits : 'FmxNGTNamed classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FAMIXCustomSourceLanguage class >> annotation [

	<generated>
	<MSEClass: #CustomSourceLanguage super: #FAMIXSourceLanguage>
	<package: #'FmxNGCompatibility-EntitiesOld'>
	<generated>
	^self
]

{ #category : #generator }
FAMIXCustomSourceLanguage class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FAMIXCustomSourceLanguage class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTNamed)
]

{ #category : #meta }
FAMIXCustomSourceLanguage class >> requirements [

	<generated>
	^ {  }
]
