Class {
	#name : #FAMIXDereferencedInvocation,
	#superclass : #FAMIXInvocation,
	#traits : 'FmxNGTDereferencedInvocation',
	#classTraits : 'FmxNGTDereferencedInvocation classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FAMIXDereferencedInvocation class >> annotation [

	<generated>
	<MSEClass: #DereferencedInvocation super: #FAMIXInvocation>
	<package: #FAMIX>
	<generated>
	^self
]

{ #category : #generator }
FAMIXDereferencedInvocation class >> generatedSlotNames [
	<generated>
	'FAMIXDereferencedInvocation class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FAMIXDereferencedInvocation class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTDereferencedInvocation)
]

{ #category : #meta }
FAMIXDereferencedInvocation class >> requirements [

	<generated>
	^ {  }
]
