Class {
	#name : #FAMIXDeclaredException,
	#superclass : #FAMIXException,
	#traits : 'FmxNGTDeclaredException',
	#classTraits : 'FmxNGTDeclaredException classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FAMIXDeclaredException class >> annotation [

	<generated>
	<MSEClass: #DeclaredException super: #FAMIXException>
	<package: #FAMIX>
	<generated>
	^self
]

{ #category : #generator }
FAMIXDeclaredException class >> generatedSlotNames [
	<generated>
	'FAMIXDeclaredException class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FAMIXDeclaredException class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTDeclaredException)
]

{ #category : #meta }
FAMIXDeclaredException class >> requirements [

	<generated>
	^ {  }
]
