Class {
	#name : #FAMIXTrait,
	#superclass : #FAMIXType,
	#traits : 'FmxNGTTrait',
	#classTraits : 'FmxNGTTrait classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FAMIXTrait class >> annotation [

	<generated>
	<MSEClass: #Trait super: #FAMIXType>
	<package: #FAMIX>
	<generated>
	^self
]

{ #category : #generator }
FAMIXTrait class >> generatedSlotNames [
	<generated>
	'FAMIXTrait class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FAMIXTrait class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTTrait)
]

{ #category : #meta }
FAMIXTrait class >> requirements [

	<generated>
	^ {  }
]
