Class {
	#name : #FmxNGTypeAlias,
	#superclass : #FmxNGType,
	#traits : 'FmxNGTTypeAlias',
	#classTraits : 'FmxNGTTypeAlias classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGTypeAlias class >> annotation [

	<generated>
	<MSEClass: #TypeAlias super: #FmxNGType>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGTypeAlias class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGTypeAlias class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTTypeAlias)
]

{ #category : #meta }
FmxNGTypeAlias class >> requirements [

	<generated>
	^ {  }
]
