Class {
	#name : #FmxNGSourceAnchor,
	#superclass : #FmxNGEntity,
	#traits : 'FmxNGTSourceAnchor',
	#classTraits : 'FmxNGTSourceAnchor classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGSourceAnchor class >> annotation [

	<generated>
	<MSEClass: #SourceAnchor super: #FmxNGEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGSourceAnchor class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGSourceAnchor class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTSourceAnchor)
]

{ #category : #meta }
FmxNGSourceAnchor class >> requirements [

	<generated>
	^ {  }
]
