Class {
	#name : #FmxNGPreprocessorDefine,
	#superclass : #FmxNGPreprocessorStatement,
	#traits : 'FmxNGTPreprocessorIfdef',
	#classTraits : 'FmxNGTPreprocessorIfdef classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGPreprocessorDefine class >> annotation [

	<generated>
	<MSEClass: #PreprocessorDefine super: #FmxNGPreprocessorStatement>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGPreprocessorDefine class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGPreprocessorDefine class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTPreprocessorIfdef)
]

{ #category : #meta }
FmxNGPreprocessorDefine class >> requirements [

	<generated>
	^ {  }
]
