Class {
	#name : #FmxNGEnumValue,
	#superclass : #FmxNGStructuralEntity,
	#traits : 'FmxNGTEnumValue',
	#classTraits : 'FmxNGTEnumValue classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGEnumValue class >> annotation [

	<generated>
	<MSEClass: #EnumValue super: #FmxNGStructuralEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGEnumValue class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGEnumValue class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTEnumValue)
]

{ #category : #meta }
FmxNGEnumValue class >> requirements [

	<generated>
	^ {  }
]
