Class {
	#name : #FmxNGCPPSourceLanguage,
	#superclass : #FmxNGCSourceLanguage,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGCPPSourceLanguage class >> annotation [

	<generated>
	<MSEClass: #CPPSourceLanguage super: #FmxNGCSourceLanguage>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGCPPSourceLanguage class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGCPPSourceLanguage class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGCPPSourceLanguage class >> requirements [

	<generated>
	^ {  }
]
