Class {
	#name : #FmxNGFolder,
	#superclass : #FmxNGEntity,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGFolder class >> annotation [

	<generated>
	<MSEClass: #Folder super: #FmxNGEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGFolder class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGFolder class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGFolder class >> requirements [

	<generated>
	^ {  }
]
