Class {
	#name : #FmxNGIndexedFileAnchor,
	#superclass : #FmxNGAbstractFileAnchor,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGIndexedFileAnchor class >> annotation [

	<generated>
	<MSEClass: #IndexedFileAnchor super: #FmxNGAbstractFileAnchor>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGIndexedFileAnchor class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGIndexedFileAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGIndexedFileAnchor class >> requirements [

	<generated>
	^ {  }
]
