Class {
	#name : #FmxNGBehaviouralEntity,
	#superclass : #FmxNGContainerEntity,
	#traits : 'FmxNGTInvocable + FmxNGTTypedStructure + FmxNGTWithAccesses + FmxNGTWithDereferencedInvocations + FmxNGTWithImplicitVariables + FmxNGTWithInvocations + FmxNGTWithLocalVariables + FmxNGTWithParameters + FmxNGTWithReferences + FmxNGTWithSignature',
	#classTraits : 'FmxNGTInvocable classTrait + FmxNGTTypedStructure classTrait + FmxNGTWithAccesses classTrait + FmxNGTWithDereferencedInvocations classTrait + FmxNGTWithImplicitVariables classTrait + FmxNGTWithInvocations classTrait + FmxNGTWithLocalVariables classTrait + FmxNGTWithParameters classTrait + FmxNGTWithReferences classTrait + FmxNGTWithSignature classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGBehaviouralEntity class >> annotation [

	<generated>
	<MSEClass: #BehaviouralEntity super: #FmxNGContainerEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGBehaviouralEntity class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGBehaviouralEntity class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTInvocable FmxNGTTypedStructure FmxNGTWithAccesses FmxNGTWithDereferencedInvocations FmxNGTWithImplicitVariables FmxNGTWithInvocations FmxNGTWithLocalVariables FmxNGTWithParameters FmxNGTWithReferences FmxNGTWithSignature)
]

{ #category : #meta }
FmxNGBehaviouralEntity class >> requirements [

	<generated>
	^ {  }
]
