Class {
	#name : #FmxNGPharoAnchor,
	#superclass : #FmxNGSourceAnchor,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGPharoAnchor class >> annotation [

	<generated>
	<MSEClass: #PharoAnchor super: #FmxNGSourceAnchor>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGPharoAnchor class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGPharoAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGPharoAnchor class >> requirements [

	<generated>
	^ {  }
]
