Class {
	#name : #FmxNGEntity,
	#superclass : #MooseEntity,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGEntity class >> annotation [

	<generated>
	<MSEClass: #Entity super: #MooseEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGEntity class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGEntity class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGEntity class >> metamodel [

	<generated>
	^ FmxNGCompatibilityGenerator metamodel
]

{ #category : #meta }
FmxNGEntity class >> requirements [

	<generated>
	^ {  }
]
