Class {
	#name : #FmxNGPreprocessorStatement,
	#superclass : #FmxNGSourcedEntity,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGPreprocessorStatement class >> annotation [

	<generated>
	<MSEClass: #PreprocessorStatement super: #FmxNGSourcedEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGPreprocessorStatement class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGPreprocessorStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGPreprocessorStatement class >> requirements [

	<generated>
	^ {  }
]
