Class {
	#name : #FmxNGPreprocessorIfdef,
	#superclass : #FmxNGPreprocessorStatement,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGPreprocessorIfdef class >> annotation [

	<generated>
	<MSEClass: #PreprocessorIfdef super: #FmxNGPreprocessorStatement>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGPreprocessorIfdef class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGPreprocessorIfdef class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGPreprocessorIfdef class >> requirements [

	<generated>
	^ {  }
]
