Class {
	#name : #FmxNGReference,
	#superclass : #FmxNGAssociation,
	#traits : 'FmxNGTReference',
	#classTraits : 'FmxNGTReference classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGReference class >> annotation [

	<generated>
	<MSEClass: #Reference super: #FmxNGAssociation>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGReference class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGReference class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTReference)
]

{ #category : #meta }
FmxNGReference class >> requirements [

	<generated>
	^ {  }
]
