Class {
	#name : #FmxNGNamespace,
	#superclass : #FmxNGScopingEntity,
	#traits : 'FmxNGTNamespace',
	#classTraits : 'FmxNGTNamespace classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGNamespace class >> annotation [

	<generated>
	<MSEClass: #Namespace super: #FmxNGScopingEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGNamespace class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGNamespace class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTNamespace)
]

{ #category : #meta }
FmxNGNamespace class >> requirements [

	<generated>
	^ {  }
]
