Class {
	#name : #FmxNGUnknownVariable,
	#superclass : #FmxNGStructuralEntity,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGUnknownVariable class >> annotation [

	<generated>
	<MSEClass: #UnknownVariable super: #FmxNGStructuralEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGUnknownVariable class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGUnknownVariable class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGUnknownVariable class >> requirements [

	<generated>
	^ {  }
]
