Class {
	#name : #FmxNGMultipleFileAnchor,
	#superclass : #FmxNGSourceAnchor,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGMultipleFileAnchor class >> annotation [

	<generated>
	<MSEClass: #MultipleFileAnchor super: #FmxNGSourceAnchor>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGMultipleFileAnchor class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGMultipleFileAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGMultipleFileAnchor class >> requirements [

	<generated>
	^ {  }
]
