Class {
	#name : #FmxNGParameterType,
	#superclass : #FmxNGType,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGParameterType class >> annotation [

	<generated>
	<MSEClass: #ParameterType super: #FmxNGType>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGParameterType class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGParameterType class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGParameterType class >> requirements [

	<generated>
	^ {  }
]
