Class {
	#name : #FmxNGThrownException,
	#superclass : #FmxNGException,
	#traits : 'FmxNGTThrownException',
	#classTraits : 'FmxNGTThrownException classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGThrownException class >> annotation [

	<generated>
	<MSEClass: #ThrownException super: #FmxNGException>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGThrownException class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGThrownException class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTThrownException)
]

{ #category : #meta }
FmxNGThrownException class >> requirements [

	<generated>
	^ {  }
]
