Class {
	#name : #FmxNGPackage,
	#superclass : #FmxNGScopingEntity,
	#traits : 'FmxNGTPackage',
	#classTraits : 'FmxNGTPackage classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGPackage class >> annotation [

	<generated>
	<MSEClass: #Package super: #FmxNGScopingEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGPackage class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGPackage class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTPackage)
]

{ #category : #meta }
FmxNGPackage class >> requirements [

	<generated>
	^ {  }
]
