Class {
	#name : #FmxNGComment,
	#superclass : #FmxNGSourcedEntity,
	#traits : 'FmxNGTComment',
	#classTraits : 'FmxNGTComment classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGComment class >> annotation [

	<generated>
	<MSEClass: #Comment super: #FmxNGSourcedEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGComment class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGComment class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTComment)
]

{ #category : #meta }
FmxNGComment class >> requirements [

	<generated>
	^ {  }
]
