Class {
	#name : #FmxNGUNKNOWNSourceLanguage,
	#superclass : #FmxNGUNKNOWNSourceLanguageGenerated,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGUNKNOWNSourceLanguage class >> annotation [

	<MSEClass: #UNKNOWNSourceLanguage super: #FmxNGUNKNOWNSourceLanguageGenerated>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #testing }
FmxNGUNKNOWNSourceLanguage >> isUnknown [ 
	^ true
]
