Class {
	#name : #FmxNGCaughtException,
	#superclass : #FmxNGException,
	#traits : 'FmxNGTCaughtException',
	#classTraits : 'FmxNGTCaughtException classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGCaughtException class >> annotation [

	<generated>
	<MSEClass: #CaughtException super: #FmxNGException>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGCaughtException class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGCaughtException class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTCaughtException)
]

{ #category : #meta }
FmxNGCaughtException class >> requirements [

	<generated>
	^ {  }
]
