Class {
	#name : #FmxNGParameter,
	#superclass : #FmxNGStructuralEntity,
	#traits : 'FmxNGTParameter',
	#classTraits : 'FmxNGTParameter classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGParameter class >> annotation [

	<generated>
	<MSEClass: #Parameter super: #FmxNGStructuralEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGParameter class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGParameter class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTParameter)
]

{ #category : #meta }
FmxNGParameter class >> requirements [

	<generated>
	^ {  }
]
