Class {
	#name : #FmxNGAbstractFile,
	#superclass : #FmxNGNamedEntity,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGAbstractFile class >> annotation [

	<generated>
	<MSEClass: #AbstractFile super: #FmxNGNamedEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGAbstractFile class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGAbstractFile class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGAbstractFile class >> requirements [

	<generated>
	^ {  }
]
