Class {
	#name : #FmxNGClass,
	#superclass : #FmxNGType,
	#traits : 'FmxNGTWithExceptions',
	#classTraits : 'FmxNGTWithExceptions classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGClass class >> annotation [

	<generated>
	<MSEClass: #Class super: #FmxNGType>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGClass class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGClass class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTWithExceptions)
]

{ #category : #meta }
FmxNGClass class >> requirements [

	<generated>
	^ {  }
]
