Class {
	#name : #FmxNGCUSTOMSourceLanguage,
	#superclass : #FmxNGSourceLanguage,
	#traits : 'FmxNGTNamed',
	#classTraits : 'FmxNGTNamed classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGCUSTOMSourceLanguage class >> annotation [

	<generated>
	<MSEClass: #CUSTOMSourceLanguage super: #FmxNGSourceLanguage>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGCUSTOMSourceLanguage class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGCUSTOMSourceLanguage class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTNamed)
]

{ #category : #meta }
FmxNGCUSTOMSourceLanguage class >> requirements [

	<generated>
	^ {  }
]
