Class {
	#name : #FmxNGCFile,
	#superclass : #FmxNGFile,
	#traits : 'FmxNGTWithFileInclude',
	#classTraits : 'FmxNGTWithFileInclude classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGCFile class >> annotation [

	<generated>
	<MSEClass: #CFile super: #FmxNGFile>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGCFile class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGCFile class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTWithFileInclude)
]

{ #category : #meta }
FmxNGCFile class >> requirements [

	<generated>
	^ {  }
]
