Class {
	#name : #FmxNGFileAnchor,
	#superclass : #FmxNGAbstractFileAnchor,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGFileAnchor class >> annotation [

	<generated>
	<MSEClass: #FileAnchor super: #FmxNGAbstractFileAnchor>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGFileAnchor class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGFileAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGFileAnchor class >> requirements [

	<generated>
	^ {  }
]
