Class {
	#name : #FmxNGPrimitiveType,
	#superclass : #FmxNGType,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGPrimitiveType class >> annotation [

	<generated>
	<MSEClass: #PrimitiveType super: #FmxNGType>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGPrimitiveType class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGPrimitiveType class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGPrimitiveType class >> requirements [

	<generated>
	^ {  }
]

{ #category : #testing }
FmxNGPrimitiveType >> isPrimitiveType [
	^true
]
