Class {
	#name : #FmxNGJAVASourceLanguage,
	#superclass : #FmxNGJAVASourceLanguageGenerated,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGJAVASourceLanguage class >> annotation [

	<MSEClass: #JAVASourceLanguage super: #FmxNGJAVASourceLanguageGenerated>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #testing }
FmxNGJAVASourceLanguage >> isUnknown [ 
	^ true
]
