Class {
	#name : #FmxNGTraitUsage,
	#superclass : #FmxNGAssociation,
	#traits : 'FmxNGTTraitUsage',
	#classTraits : 'FmxNGTTraitUsage classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGTraitUsage class >> annotation [

	<generated>
	<MSEClass: #TraitUsage super: #FmxNGAssociation>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGTraitUsage class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGTraitUsage class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTTraitUsage)
]

{ #category : #meta }
FmxNGTraitUsage class >> requirements [

	<generated>
	^ {  }
]
