Class {
	#name : #FmxNGAccess,
	#superclass : #FmxNGAssociation,
	#traits : 'FmxNGTAccess',
	#classTraits : 'FmxNGTAccess classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGAccess class >> annotation [

	<generated>
	<MSEClass: #Access super: #FmxNGAssociation>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGAccess class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGAccess class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTAccess)
]

{ #category : #meta }
FmxNGAccess class >> requirements [

	<generated>
	^ {  }
]
