Class {
	#name : #FmxNGImplicitVariable,
	#superclass : #FmxNGStructuralEntity,
	#traits : 'FmxNGTImplicitVariable',
	#classTraits : 'FmxNGTImplicitVariable classTrait',
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGImplicitVariable class >> annotation [

	<generated>
	<MSEClass: #ImplicitVariable super: #FmxNGStructuralEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGImplicitVariable class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGImplicitVariable class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTImplicitVariable)
]

{ #category : #meta }
FmxNGImplicitVariable class >> requirements [

	<generated>
	^ {  }
]
