Class {
	#name : #FmxNGLeafEntity,
	#superclass : #FmxNGNamedEntity,
	#category : #'FmxNGCompatibility-Entities-Entities'
}

{ #category : #meta }
FmxNGLeafEntity class >> annotation [

	<generated>
	<MSEClass: #LeafEntity super: #FmxNGNamedEntity>
	<package: #'FmxNGCompatibility-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGLeafEntity class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
FmxNGLeafEntity class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGLeafEntity class >> requirements [

	<generated>
	^ {  }
]
