statements-elements
columnTypes 
	^
	'VARCHAR2' asPParser caseInsensitive trim /
	'VARCHAR' asPParser caseInsensitive trim / "MySQL specific type"
	'CLOB' asPParser caseInsensitive trim / 
	'timestamp' asPParser caseInsensitive trim /
	'NUMBER' asPParser caseInsensitive trim / 
	'DATE' asPParser caseInsensitive trim / 
	'integer' asPParser caseInsensitive trim / 
	'boolean' asPParser caseInsensitive trim / 
	'blob' asPParser caseInsensitive trim / 
	'CHARACTER' asPParser caseInsensitive trim / "postgress specfic type"
	'char' asPParser caseInsensitive trim / 
	'int' asPParser caseInsensitive trim /
	'NVARCHAR2' asPParser caseInsensitive trim /
	'FLOAT' asPParser caseInsensitive trim /
	'RAW' asPParser caseInsensitive trim /
	'longtext' asPParser caseInsensitive trim / "MySQL specific type"
	'LONG' asPParser caseInsensitive trim /
	'NUMERIC' asPParser caseInsensitive trim / "postgress specfic type"
	'bytea' asPParser caseInsensitive trim / "postgress specfic type"
	'text' asPParser caseInsensitive trim / "postgress specfic type"
	'name' asPParser caseInsensitive trim / "postgress specfic type"
	'bigint' asPParser caseInsensitive trim / "MySQL specific type"
	'bit' asPParser caseInsensitive trim / "MySQL specific type"
	'varbinary' asPParser caseInsensitive trim / "MySQL specific type"
	'double' asPParser caseInsensitive trim / "MySQL specific type"
	'decimal' asPParser caseInsensitive trim / "MySQL specific type"
	'smallint' asPParser caseInsensitive trim. "MySQL specific type"