Trait {
	#name : #FmxNGTInheritanceGlue,
	#category : #'FmxNG-Traits-Traits'
}

{ #category : #meta }
FmxNGTInheritanceGlue classSide >> annotation [

	<MSEClass: #TInheritanceGlue super: #Trait>
	<generated>
	<package: #'FmxNG-Traits'>
	^self
]

{ #category : #generator }
FmxNGTInheritanceGlue classSide >> generatedSlotNames [
	<generated>
	'FmxNGTInheritanceGlue class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGTInheritanceGlue classSide >> generatedTraitNames [
	<generated>
	^ #()
]
