Trait {
	#name : #FmxNGTWithParameterizedTypes,
	#category : #'FmxNG-Traits-Traits'
}

{ #category : #meta }
FmxNGTWithParameterizedTypes classSide >> annotation [

	<generated>
	<ignoreInTraitUsers>
	<MSEClass: #TWithParameterizedTypes super: #Trait>
	<generated>
	<package: #'FmxNG-Traits'>
	^self
]

{ #category : #generator }
FmxNGTWithParameterizedTypes classSide >> generatedSlotNames [
	<generated>
	^ #(parameterizedTypes)
]

{ #category : #generator }
FmxNGTWithParameterizedTypes classSide >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #accessing }
FmxNGTWithParameterizedTypes >> parameterizedTypes [

	<generated>
	^ parameterizedTypes
]

{ #category : #accessing }
FmxNGTWithParameterizedTypes >> parameterizedTypes: anObject [

	<generated>
	parameterizedTypes value: anObject

]
