Trait {
	#name : #FmxNGTParameterizedTypeUser,
	#category : #'FmxNG-Traits-Traits'
}

{ #category : #meta }
FmxNGTParameterizedTypeUser classSide >> annotation [

	<generated>
	<ignoreInTraitUsers>
	<MSEClass: #TParameterizedTypeUser super: #Trait>
	<generated>
	<package: #'FmxNG-Traits'>
	^self
]

{ #category : #generator }
FmxNGTParameterizedTypeUser classSide >> generatedSlotNames [
	<generated>
	^ #(argumentsInParameterizedTypes)
]

{ #category : #generator }
FmxNGTParameterizedTypeUser classSide >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #accessing }
FmxNGTParameterizedTypeUser >> argumentsInParameterizedTypes [

	<generated>
	^ argumentsInParameterizedTypes
]

{ #category : #accessing }
FmxNGTParameterizedTypeUser >> argumentsInParameterizedTypes: anObject [

	<generated>
	argumentsInParameterizedTypes := anObject

]
