setUp
file1 
	 
	^' 
    			fclose( hFrom ) ; 
    			fclose( hTo ) ; 
    			return ; 
    		} 
    		if ( feof( hFrom ) ) 
    			break ; 
    		fputc( c, hTo ) ; 
    		if ( ferror( hTo ) ) 
    		{ 
    			printf( "\nCF write error - ende\n" ) ; 
    			fclose( hFrom ) ; 
    			fclose( hTo ) ; 
    			return ; 
 
asdfasdf 
sdfasdf 
sdfsadf 
ghasdjfghj 
 
 
    			fclose( hFrom ) ; 
    			fclose( hTo ) ; 
    			return ; 
    		} 
    		if ( feof( hFrom ) ) 
    			break ; 
    		fputc( c, hTo ) ; 
    		if ( ferror( hTo ) ) 
    		{ 
    			printf( "\nCF write error - ende\n" ) ; 
    			fclose( hFrom ) ; 
    			fclose( hTo ) ; 
    			return ; 
 
fghfghj 
fghjfghj 
gfhjgfhj 
ghjfghj 
 
 
    			fclose( hFrom ) ; 
    			fclose( hTo ) ; 
    			return ; 
    		} 
    		if ( feof( hFrom ) ) 
    			break ; 
    		fputc( c, hTo ) ; 
    		if ( ferror( hTo ) ) 
    		{ 
    			printf( "\nCF write error - ende\n" ) ; 
    			fclose( hFrom ) ; 
    			fclose( hTo ) ; 
    			return ; 
'