accessing
visibility
	"Specifies the visibility of the imported PackageableElements within the importingNamespace, i.e., whether imported Elements will in turn be visible to other Namespaces. If the PackageImport is public, the imported Elements will be visible outside the importingNamespace, while, if the PackageImport is private, they will not."
	^ visibility ifNil: [ visibility := OPUMLVisibilityKind new public ]