example-data
gtinspector
	^ 'time	n1	n2 	weight
51	GTExample	AndreiChis	1
51	GTExample	StefanReichhart	3
47	GTExample	StefanReichhart	15
46	GTExample	StefanReichhart	10
49	GTExample	StefanReichhart	58
52	GTExample	StefanReichhart	5
48	GTExample	StefanReichhart	19
49	GTExampleFinder	StefanReichhart	12
48	GTExampleFinder	StefanReichhart	6
47	GTExampleFinder	StefanReichhart	2
46	GTExampleFinder	StefanReichhart	4
49	GTExampleResult	StefanReichhart	1
48	GTExampleResult	StefanReichhart	14
52	GTExampleResult	StefanReichhart	1
46	GTExampleResult	StefanReichhart	2
49	GTExampleProcessor	StefanReichhart	9
48	GTExampleProcessor	StefanReichhart	8
47	GTExampleProcessor	StefanReichhart	7
40	GTInspectorMethodListFilter	AndreiChis	12
49	GTExampleProxy	StefanReichhart	3
48	GTExampleProxy	StefanReichhart	16
47	GTExampleProxy	StefanReichhart	5
46	GTExampleProxy	StefanReichhart	2
40	GTInspectorTagFilter	AndreiChis	11
41	GTInspectorTagFilter	AndreiChis	2
51	GTExampleOrganizer	AndreiChis	3
47	GTExampleOrganizer	StefanReichhart	5
46	GTExampleOrganizer	StefanReichhart	1
49	GTExampleOrganizer	StefanReichhart	21
48	GTExampleOrganizer	StefanReichhart	2
0	GTInspector	TudorGirba	1
40	GTInspector	AndreiChis	1
40	GTInspector	EstebanLorenzano	1
36	GTInspector	AndreiChis	3
44	GTInspector	TudorGirba	1
31	GTInspector	TudorGirba	2
38	GTInspector	AndreiChis	3
38	GTInspector	SvenVanCaekenberghe	1
41	GTInspector	AndreiChis	6
49	GTExampleNautilus	StefanReichhart	2
52	GTExampleNautilus	StefanReichhart	5
51	GTExampleNautilus	JurajKubelka	2
'