todo
fameTodos '
[ ] Implement FMRepository >> #completeAdd:, which follows ALL meta-described navigation.
[ ] Implement FMRepository >> #compositeAdd:, which follows OWNERSHIP meta-described navigation.
[ ] Implement FMRepository >> #completeDelete:, which follows ALL meta-described navigation.
[ ] Implement FMRepository >> #compositeDelete:, which follows OWNERSHIP meta-described navigation.
[ ] Please dont annotate the test method to test annotations (just use a example class)
[x] Fix issues with the parser.
[x] Test that annotation updating works when rerunning a test
[x] Rewrite all those moron tests (and mail people not to use math or loops in tests!)
[x] Teach people to never commit if tests fail
[x] See that all developers are on fame-dev mailing list
[x] Have a look at how the setup of Fame towers works?
[x] Get rid of the #defaultDescriptionFor: cancer!
[x] Fix #asFameDescription
[x] Hunt down all singeltons and remove them'	