accessing
packagedElements
	"The set of PackageableElements that a Component owns. In the namespace of a Component, all model elements that are involved in or related to its definition may be owned or imported explicitly. These may include e.g., Classes, Interfaces, Components, Packages, UseCases, Dependencies (e.g., mappings), and Artifacts."
	^ packagedElements ifNil: [ packagedElements := OrderedCollection new ]