Class {
	#name : #FamixMetamodelBuilderVisitor,
	#superclass : #Object,
	#category : #'Famix-MetamodelBuilder-Core'
}

{ #category : #visiting }
FamixMetamodelBuilderVisitor >> visitBuilder: aBuilder [

	
]

{ #category : #visiting }
FamixMetamodelBuilderVisitor >> visitClass: aClas [
]

{ #category : #visiting }
FamixMetamodelBuilderVisitor >> visitRelationSide: aRelationSide [
]

{ #category : #visiting }
FamixMetamodelBuilderVisitor >> visitTrait: aTrait [
]

{ #category : #visiting }
FamixMetamodelBuilderVisitor >> visitTypedProperty: aTypedProperty [
]
