Class {
	#name : #FmxCTypeGenerated,
	#superclass : #FmxCEntity,
	#category : #'FmxC-Generated-Entities'
}

{ #category : #meta }
FmxCTypeGenerated class >> annotation [

	<MSEClass: #TypeGenerated super: #FmxCEntity>
	<package: #'FmxC-Generated'>
	^self
]

{ #category : #meta }
FmxCTypeGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxCTypeGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
