SystemOrganization addCategory: #'OpenPonk-UML-DI'!
SystemOrganization addCategory: 'OpenPonk-UML-DI-DiagramInterchange'!
SystemOrganization addCategory: 'OpenPonk-UML-DI-Examples'!
SystemOrganization addCategory: 'OpenPonk-UML-DI-Facades'!
SystemOrganization addCategory: 'OpenPonk-UML-DI-Roassal'!
SystemOrganization addCategory: 'OpenPonk-UML-DI-Tests'!
SystemOrganization addCategory: 'OpenPonk-UML-DI-Trachel'!
SystemOrganization addCategory: 'OpenPonk-UML-DI-UML'!
