accessing
instrumentationContextFrom: aContext

	^ aContext  "GTPPStepToNextProductionReflectivityAction(GTReflectivityDebugAction)>>openDebuggerForBreakpoint:"
		sender   "GTPPStepToNextProductionReflectivityAction(GTReflectivityDebugAction)>>breakpointReachedFrom:"
		sender   "GTDebuggerMethodEntryBreakpoint(GTDebuggerBrekpoint)>>breakpointReached"
		sender   "Instrumented method -> at the beginning after sending breakpointReached"