Class {
	#name : #FmxNGJavaReference,
	#superclass : #FmxNGJavaAssociation,
	#traits : 'FmxNGTReference',
	#classTraits : 'FmxNGTReference classTrait',
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaReference class >> annotation [

	<generated>
	<MSEClass: #Reference super: #FmxNGJavaAssociation>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaReference class >> generatedSlotNames [
	<generated>
	'FmxNGJavaReference class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaReference class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTReference)
]

{ #category : #meta }
FmxNGJavaReference class >> requirements [

	<generated>
	^ {  }
]
