Class {
	#name : #FmxNGJavaNamespace,
	#superclass : #FmxNGJavaScopingEntity,
	#traits : 'FmxNGTNamespace',
	#classTraits : 'FmxNGTNamespace classTrait',
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaNamespace class >> annotation [

	<generated>
	<MSEClass: #Namespace super: #FmxNGJavaScopingEntity>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaNamespace class >> generatedSlotNames [
	<generated>
	'FmxNGJavaNamespace class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaNamespace class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTNamespace)
]

{ #category : #meta }
FmxNGJavaNamespace class >> requirements [

	<generated>
	^ {  }
]
