Class {
	#name : #FmxNGJavaException,
	#superclass : #FmxNGJavaEntity,
	#traits : 'FmxNGTException',
	#classTraits : 'FmxNGTException classTrait',
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaException class >> annotation [

	<generated>
	<MSEClass: #Exception super: #FmxNGJavaEntity>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaException class >> generatedSlotNames [
	<generated>
	'FmxNGJavaException class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaException class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTException)
]

{ #category : #meta }
FmxNGJavaException class >> requirements [

	<generated>
	^ {  }
]
