Class {
	#name : #FmxNGJavaComment,
	#superclass : #FmxNGJavaSourcedEntity,
	#traits : 'FmxNGTComment',
	#classTraits : 'FmxNGTComment classTrait',
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaComment class >> annotation [

	<generated>
	<MSEClass: #Comment super: #FmxNGJavaSourcedEntity>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaComment class >> generatedSlotNames [
	<generated>
	'FmxNGJavaComment class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaComment class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTComment)
]

{ #category : #meta }
FmxNGJavaComment class >> requirements [

	<generated>
	^ {  }
]
