Class {
	#name : #FmxNGJavaAccess,
	#superclass : #FmxNGJavaAssociation,
	#traits : 'FmxNGTAccess',
	#classTraits : 'FmxNGTAccess classTrait',
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaAccess class >> annotation [

	<generated>
	<MSEClass: #Access super: #FmxNGJavaAssociation>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaAccess class >> generatedSlotNames [
	<generated>
	'FmxNGJavaAccess class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaAccess class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTAccess)
]

{ #category : #meta }
FmxNGJavaAccess class >> requirements [

	<generated>
	^ {  }
]
