Class {
	#name : #FmxNGJavaThrownException,
	#superclass : #FmxNGJavaException,
	#traits : 'FmxNGTThrownException',
	#classTraits : 'FmxNGTThrownException classTrait',
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaThrownException class >> annotation [

	<generated>
	<MSEClass: #ThrownException super: #FmxNGJavaException>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaThrownException class >> generatedSlotNames [
	<generated>
	'FmxNGJavaThrownException class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaThrownException class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTThrownException)
]

{ #category : #meta }
FmxNGJavaThrownException class >> requirements [

	<generated>
	^ {  }
]
