Class {
	#name : #FmxNGJavaAssociation,
	#superclass : #FmxNGJavaSourcedEntity,
	#traits : 'FmxNGTAssociation',
	#classTraits : 'FmxNGTAssociation classTrait',
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaAssociation class >> annotation [

	<generated>
	<MSEClass: #Association super: #FmxNGJavaSourcedEntity>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaAssociation class >> generatedSlotNames [
	<generated>
	'FmxNGJavaAssociation class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaAssociation class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTAssociation)
]

{ #category : #meta }
FmxNGJavaAssociation class >> requirements [

	<generated>
	^ {  }
]
