Class {
	#name : #FmxNGJavaAbstractFile,
	#superclass : #FmxNGJavaNamedEntity,
	#traits : 'FmxNGTFileSystemEntity',
	#classTraits : 'FmxNGTFileSystemEntity classTrait',
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaAbstractFile class >> annotation [

	<generated>
	<MSEClass: #AbstractFile super: #FmxNGJavaNamedEntity>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaAbstractFile class >> generatedSlotNames [
	<generated>
	'FmxNGJavaAbstractFile class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaAbstractFile class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTFileSystemEntity)
]

{ #category : #meta }
FmxNGJavaAbstractFile class >> requirements [

	<generated>
	^ {  }
]
