Class {
	#name : #FmxNGJavaFileAnchor,
	#superclass : #FmxNGJavaAbstractFileAnchor,
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaFileAnchor class >> annotation [

	<generated>
	<MSEClass: #FileAnchor super: #FmxNGJavaAbstractFileAnchor>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaFileAnchor class >> generatedSlotNames [
	<generated>
	'FmxNGJavaFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaFileAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGJavaFileAnchor class >> requirements [

	<generated>
	^ {  }
]
