Class {
	#name : #FmxNGJavaMultipleFileAnchor,
	#superclass : #FmxNGJavaSourceAnchor,
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaMultipleFileAnchor class >> annotation [

	<generated>
	<MSEClass: #MultipleFileAnchor super: #FmxNGJavaSourceAnchor>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaMultipleFileAnchor class >> generatedSlotNames [
	<generated>
	'FmxNGJavaMultipleFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaMultipleFileAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGJavaMultipleFileAnchor class >> requirements [

	<generated>
	^ {  }
]
