Class {
	#name : #FmxNGJavaParameterizableClass,
	#superclass : #FmxNGJavaClass,
	#traits : 'FmxNGTWithParameterizedTypes',
	#classTraits : 'FmxNGTWithParameterizedTypes classTrait',
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaParameterizableClass class >> annotation [

	<generated>
	<MSEClass: #ParameterizableClass super: #FmxNGJavaClass>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaParameterizableClass class >> generatedSlotNames [
	<generated>
	'FmxNGJavaParameterizableClass class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaParameterizableClass class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTWithParameterizedTypes)
]

{ #category : #meta }
FmxNGJavaParameterizableClass class >> requirements [

	<generated>
	^ {  }
]
