Class {
	#name : #FmxNGJavaSourceTextAnchor,
	#superclass : #FmxNGJavaSourceAnchor,
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaSourceTextAnchor class >> annotation [

	<generated>
	<MSEClass: #SourceTextAnchor super: #FmxNGJavaSourceAnchor>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaSourceTextAnchor class >> generatedSlotNames [
	<generated>
	'FmxNGJavaSourceTextAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaSourceTextAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGJavaSourceTextAnchor class >> requirements [

	<generated>
	^ {  }
]
