Class {
	#name : #FmxNGJavaFile,
	#superclass : #FmxNGJavaAbstractFile,
	#traits : 'FmxNGTFile',
	#classTraits : 'FmxNGTFile classTrait',
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaFile class >> annotation [

	<generated>
	<MSEClass: #File super: #FmxNGJavaAbstractFile>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaFile class >> generatedSlotNames [
	<generated>
	'FmxNGJavaFile class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaFile class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTFile)
]

{ #category : #meta }
FmxNGJavaFile class >> requirements [

	<generated>
	^ {  }
]
