Class {
	#name : #FmxNGJavaIndexedFileAnchor,
	#superclass : #FmxNGJavaAbstractFileAnchor,
	#category : #'FmxNGJava-Entities-Entities'
}

{ #category : #meta }
FmxNGJavaIndexedFileAnchor class >> annotation [

	<generated>
	<MSEClass: #IndexedFileAnchor super: #FmxNGJavaAbstractFileAnchor>
	<package: #'FmxNGJava-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGJavaIndexedFileAnchor class >> generatedSlotNames [
	<generated>
	'FmxNGJavaIndexedFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGJavaIndexedFileAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGJavaIndexedFileAnchor class >> requirements [

	<generated>
	^ {  }
]
