class initialization
initialize
	"self initialize"

	defaultDefaultColor := nil.
	defaultAxisColor := nil.
	defaultNodeTestColor := nil.
	defaultPredicatePrimaryColor := nil.
	defaultPredicateSecondaryColor := nil.
	defaultPredicateTertiaryColor := nil.
	defaultOperatorColor := nil.
	defaultFunctionCallColor := nil.
	defaultStringLiteralColor := nil.
	defaultNumberLiteralColor := nil.
	defaultVariableReferenceColor := nil.