Class {
	#name : #FmxNGTest1ImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'FmxNGTest1-Entities'
}

{ #category : #generator }
FmxNGTest1ImportingContext class >> generatedSlotNames [
	<generated>
	'FmxNGTest1ImportingContext class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGTest1ImportingContext class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importAbstractFile [

	<generated>
	^ self import: FmxNGTest1AbstractFile
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importAbstractFileAnchor [

	<generated>
	^ self import: FmxNGTest1AbstractFileAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importAssociation [

	<generated>
	^ self import: FmxNGTest1Association
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importClass [

	<generated>
	^ self import: FmxNGTest1Class
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importComment [

	<generated>
	^ self import: FmxNGTest1Comment
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importEntity [

	<generated>
	^ self import: FmxNGTest1Entity
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importFile [

	<generated>
	^ self import: FmxNGTest1File
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importFileAnchor [

	<generated>
	^ self import: FmxNGTest1FileAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importFolder [

	<generated>
	^ self import: FmxNGTest1Folder
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importIndexedFileAnchor [

	<generated>
	^ self import: FmxNGTest1IndexedFileAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importMethod [

	<generated>
	^ self import: FmxNGTest1Method
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importMultipleFileAnchor [

	<generated>
	^ self import: FmxNGTest1MultipleFileAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importNamedEntity [

	<generated>
	^ self import: FmxNGTest1NamedEntity
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importSourceAnchor [

	<generated>
	^ self import: FmxNGTest1SourceAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importSourceLanguage [

	<generated>
	^ self import: FmxNGTest1SourceLanguage
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importSourceTextAnchor [

	<generated>
	^ self import: FmxNGTest1SourceTextAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> importSourcedEntity [

	<generated>
	^ self import: FmxNGTest1SourcedEntity
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportAbstractFile [

	<generated>
	^ self shouldImport: FmxNGTest1AbstractFile
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportAbstractFileAnchor [

	<generated>
	^ self shouldImport: FmxNGTest1AbstractFileAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportAssociation [

	<generated>
	^ self shouldImport: FmxNGTest1Association
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportClass [

	<generated>
	^ self shouldImport: FmxNGTest1Class
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportComment [

	<generated>
	^ self shouldImport: FmxNGTest1Comment
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportEntity [

	<generated>
	^ self shouldImport: FmxNGTest1Entity
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportFile [

	<generated>
	^ self shouldImport: FmxNGTest1File
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportFileAnchor [

	<generated>
	^ self shouldImport: FmxNGTest1FileAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportFolder [

	<generated>
	^ self shouldImport: FmxNGTest1Folder
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportIndexedFileAnchor [

	<generated>
	^ self shouldImport: FmxNGTest1IndexedFileAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportMethod [

	<generated>
	^ self shouldImport: FmxNGTest1Method
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportMultipleFileAnchor [

	<generated>
	^ self shouldImport: FmxNGTest1MultipleFileAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportNamedEntity [

	<generated>
	^ self shouldImport: FmxNGTest1NamedEntity
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportSourceAnchor [

	<generated>
	^ self shouldImport: FmxNGTest1SourceAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportSourceLanguage [

	<generated>
	^ self shouldImport: FmxNGTest1SourceLanguage
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportSourceTextAnchor [

	<generated>
	^ self shouldImport: FmxNGTest1SourceTextAnchor
]

{ #category : #testing }
FmxNGTest1ImportingContext >> shouldImportSourcedEntity [

	<generated>
	^ self shouldImport: FmxNGTest1SourcedEntity
]
