Class {
	#name : #FmxNGTest1MultipleFileAnchor,
	#superclass : #FmxNGTest1SourceAnchor,
	#category : #'FmxNGTest1-Entities-Entities'
}

{ #category : #meta }
FmxNGTest1MultipleFileAnchor class >> annotation [

	<MSEClass: #MultipleFileAnchor super: #FmxNGTest1SourceAnchor>
	<package: #'FmxNGTest1-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGTest1MultipleFileAnchor class >> generatedSlotNames [
	<generated>
	'FmxNGTest1MultipleFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGTest1MultipleFileAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FmxNGTest1MultipleFileAnchor class >> requirements [

	<generated>
	^ {  }
]
