Class {
	#name : #FmxNGTest1AbstractFileAnchor,
	#superclass : #FmxNGTest1SourceAnchor,
	#traits : 'FmxNGTFileAnchor',
	#classTraits : 'FmxNGTFileAnchor classTrait',
	#category : #'FmxNGTest1-Entities-Entities'
}

{ #category : #meta }
FmxNGTest1AbstractFileAnchor class >> annotation [

	<MSEClass: #AbstractFileAnchor super: #FmxNGTest1SourceAnchor>
	<package: #'FmxNGTest1-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FmxNGTest1AbstractFileAnchor class >> generatedSlotNames [
	<generated>
	'FmxNGTest1AbstractFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGTest1AbstractFileAnchor class >> generatedTraitNames [
	<generated>
	^ #(FmxNGTFileAnchor)
]

{ #category : #meta }
FmxNGTest1AbstractFileAnchor class >> requirements [

	<generated>
	^ {  }
]
