Class {
	#name : #FmxNGIndexedFileAnchorGenerated,
	#superclass : #FmxNGAbstractFileAnchor,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGIndexedFileAnchorGenerated class >> annotation [

	<MSEClass: #IndexedFileAnchorGenerated super: #FmxNGAbstractFileAnchor>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGIndexedFileAnchorGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGIndexedFileAnchorGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
