Class {
	#name : #FmxNGPreprocessorIfdefGenerated,
	#superclass : #FmxNGPreprocessorStatement,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGPreprocessorIfdefGenerated class >> annotation [

	<MSEClass: #PreprocessorIfdefGenerated super: #FmxNGPreprocessorStatement>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGPreprocessorIfdefGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGPreprocessorIfdefGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
