Class {
	#name : #FmxNGAbstractFileGenerated,
	#superclass : #FmxNGNamedEntity,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGAbstractFileGenerated class >> annotation [

	<MSEClass: #AbstractFileGenerated super: #FmxNGNamedEntity>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGAbstractFileGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGAbstractFileGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
