Class {
	#name : #FmxNGFileGenerated,
	#superclass : #FmxNGEntity,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGFileGenerated class >> annotation [

	<MSEClass: #FileGenerated super: #FmxNGEntity>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGFileGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGFileGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
