Class {
	#name : #FmxNGJAVASourceLanguageGenerated,
	#superclass : #FmxNGSourceLanguage,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGJAVASourceLanguageGenerated class >> annotation [

	<MSEClass: #JAVASourceLanguageGenerated super: #FmxNGSourceLanguage>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGJAVASourceLanguageGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGJAVASourceLanguageGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
