Class {
	#name : #FmxNGCSourceLanguageGenerated,
	#superclass : #FmxNGSourceLanguage,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGCSourceLanguageGenerated class >> annotation [

	<MSEClass: #CSourceLanguageGenerated super: #FmxNGSourceLanguage>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGCSourceLanguageGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGCSourceLanguageGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
