Class {
	#name : #FmxNGMultipleFileAnchorGenerated,
	#superclass : #FmxNGSourceAnchor,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGMultipleFileAnchorGenerated class >> annotation [

	<MSEClass: #MultipleFileAnchorGenerated super: #FmxNGSourceAnchor>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGMultipleFileAnchorGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGMultipleFileAnchorGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
