Class {
	#name : #FmxNGPreprocessorStatementGenerated,
	#superclass : #FmxNGSourcedEntity,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGPreprocessorStatementGenerated class >> annotation [

	<MSEClass: #PreprocessorStatementGenerated super: #FmxNGSourcedEntity>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGPreprocessorStatementGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGPreprocessorStatementGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
