Class {
	#name : #FmxNGPharoAnchorGenerated,
	#superclass : #FmxNGSourceAnchor,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGPharoAnchorGenerated class >> annotation [

	<MSEClass: #PharoAnchorGenerated super: #FmxNGSourceAnchor>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGPharoAnchorGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGPharoAnchorGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
