Class {
	#name : #FmxNGFileAnchorGenerated,
	#superclass : #FmxNGAbstractFileAnchor,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGFileAnchorGenerated class >> annotation [

	<MSEClass: #FileAnchorGenerated super: #FmxNGAbstractFileAnchor>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGFileAnchorGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGFileAnchorGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
