Class {
	#name : #FmxNGFolderGenerated,
	#superclass : #FmxNGEntity,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGFolderGenerated class >> annotation [

	<MSEClass: #FolderGenerated super: #FmxNGEntity>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGFolderGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGFolderGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
