Class {
	#name : #FmxNGPrimitiveTypeGenerated,
	#superclass : #FmxNGType,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGPrimitiveTypeGenerated class >> annotation [

	<MSEClass: #PrimitiveTypeGenerated super: #FmxNGType>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGPrimitiveTypeGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGPrimitiveTypeGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
