Class {
	#name : #FmxNGUNKNOWNSourceLanguageGenerated,
	#superclass : #FmxNGSourceLanguage,
	#category : #'FmxNGCompatibility-Generated-Entities'
}

{ #category : #meta }
FmxNGUNKNOWNSourceLanguageGenerated class >> annotation [

	<MSEClass: #UNKNOWNSourceLanguageGenerated super: #FmxNGSourceLanguage>
	<package: #'FmxNGCompatibility-Generated'>
	^self
]

{ #category : #meta }
FmxNGUNKNOWNSourceLanguageGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxNGUNKNOWNSourceLanguageGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
