operations - stubs
isDistinguishableFromStub
	"The query isDistinguishableFrom() specifies that two Gates may coexist in the same Namespace, without an explicit name property. The association end formalGate subsets ownedElement, and since the Gate name attribute
is optional, it is allowed to have two formal gates without an explicit name, but having derived names which are distinct."
	
	"{OCL} result = (true)"
	
	self notYetImplemented
