setup
importClasses
	
	classA := lcomModel entityNamed: #'Smalltalk::ClassA'.
	classB := lcomModel entityNamed: #'Smalltalk::ClassB'.
	classB1 := lcomModel entityNamed: #'Smalltalk::ClassB1'.
	classB2 := lcomModel entityNamed: #'Smalltalk::ClassB2'.
	classC := lcomModel entityNamed: #'Smalltalk::ClassC'.
	classD := lcomModel entityNamed: #'Smalltalk::ClassD'.
	classE := lcomModel entityNamed: #'Smalltalk::ClassE'.
	classF := lcomModel entityNamed: #'Smalltalk::ClassF'.
	classF1 := lcomModel entityNamed: #'Smalltalk::ClassF1'.
	classG := lcomModel entityNamed: #'Smalltalk::ClassG'