Trait {
	#name : #FmxNGTContainingWithInvocationsGlue,
	#category : #'FmxNG-Traits-Traits'
}

{ #category : #meta }
FmxNGTContainingWithInvocationsGlue classSide >> annotation [

	<MSEClass: #TContainingWithInvocationsGlue super: #Trait>
	<generated>
	<package: #'FmxNG-Traits'>
	^self
]

{ #category : #generator }
FmxNGTContainingWithInvocationsGlue classSide >> generatedSlotNames [
	<generated>
	'FmxNGTContainingWithInvocationsGlue class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGTContainingWithInvocationsGlue classSide >> generatedTraitNames [
	<generated>
	^ #()
]
