Trait {
	#name : #FmxNGTClassWithInvocationsGlue,
	#category : #'FmxNG-Traits-Traits'
}

{ #category : #meta }
FmxNGTClassWithInvocationsGlue classSide >> annotation [

	<MSEClass: #TClassWithInvocationsGlue super: #Trait>
	<generated>
	<package: #'FmxNG-Traits'>
	^self
]

{ #category : #generator }
FmxNGTClassWithInvocationsGlue classSide >> generatedSlotNames [
	<generated>
	'FmxNGTClassWithInvocationsGlue class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGTClassWithInvocationsGlue classSide >> generatedTraitNames [
	<generated>
	^ #()
]
