Trait {
	#name : #FmxNGTContainingWithStatementsGlue,
	#category : #'FmxNG-Traits-Traits'
}

{ #category : #meta }
FmxNGTContainingWithStatementsGlue classSide >> annotation [

	<MSEClass: #TContainingWithStatementsGlue super: #Trait>
	<generated>
	<package: #'FmxNG-Traits'>
	^self
]

{ #category : #generator }
FmxNGTContainingWithStatementsGlue classSide >> generatedSlotNames [
	<generated>
	'FmxNGTContainingWithStatementsGlue class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGTContainingWithStatementsGlue classSide >> generatedTraitNames [
	<generated>
	^ #()
]
