Trait {
	#name : #FmxNGTClassMetrics,
	#category : #'FmxNG-Traits-Support'
}

{ #category : #meta }
FmxNGTClassMetrics classSide >> annotation [

	<MSEClass: #TClassMetrics super: #Trait>
	<generated>
	<package: #'FmxNG-Traits'>
	^self
]

{ #category : #generator }
FmxNGTClassMetrics classSide >> generatedSlotNames [
	<generated>
	'FmxNGTClassMetrics class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FmxNGTClassMetrics classSide >> generatedTraitNames [
	<generated>
	^ #()
]
