accessing
commonWindowTypes

	^ #( NautilusUI
		GTPlayground
		TestRunner
		MCWorkingCopyBrowser
		FinderUI
		VersionnerSpecBrowser
		DAPackageDependenciesWelcome
		ThreadSafeTranscript
		TimeProfiler
		SelectPackageBrowser
		ProcessBrowser
		FileList
		MessageBrowser
		DualChangeSorterApplication
		ExternalChangesBrowser
		PPBrowser
		CommandShellTranscript
		AboutDialogWindow
		SettingBrowser
		GTSpecPreDebugWindow
		GTGenericStackDebugger
		GTInspector
		SystemReporter
		KeymapBrowser
		TimeProfiler
		HelpBrowser
		FileDialogWindow ).