documentation
overview
	^ HelpTopic 
		title: 'Overview'
		contents: 
'Moose is a platform for software and data analysis.

It is an open source project since 1996. It is supported by several research groups around the world, and it is increasingly adopted in industrial projects.

Moose offers multiple services ranging from importing and parsing data, to modeling, to measuring, querying, mining, and to building interactive and visual analysis tools.

More information about it can be found on the official website: http://moosetechnology.org'